# Generated by Django 2.2.11 on 2020-03-05 10:16

from django.db import migrations, models
import django_fsm
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', django_fsm.FSMField(choices=[('new', 'new'), ('pending approval', 'pending approval'), ('in progress', 'in progress'), ('completed', 'completed'), ('changes requested', 'changes requested'), ('closed', 'closed')], default='new', max_length=50, protected=True)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
